package com.framecloud.common.base.constants;


public interface FrameCloudServiceNameConstants {

    String FRAME_CLOUD_AUTH = "FRAME_CLOUD_AUTH";
    String FRAME_CLOUD_COMMON = "FRAME_CLOUD_COMMON";
    String FRAME_CLOUD_CONFIG_SERVER = "FRAME_CLOUD_CONFIG_SERVER";
    String FRAME_CLOUD_GATEWAY = "FRAME_CLOUD_GATEWAY";
    String FRAME_CLOUD_SERVER = "FRAME_CLOUD_SERVER";
    String FRAME_CLOUD_USER_SERVICE = "FRAME_CLOUD_USER_SERVICE";
    String FRAME_CLOUD_LOG_SERVICE = "FRAME_CLOUD_LOG_SERVICE";
    String FRAME_CLOUD_GEN_SERVICE = "FRAME_CLOUD_GEN_SERVICE";

}
